### ISSUE TITLE
info関数について

### ISSUE THREAD

**Issue by sumi21japan** [jumilla/wordpress-plus#1]
info()がある所でエラーになりますが、どうやって回避されているのでしょうか？

**Comment by jumilla** [comment]
info()はLaravelで定義されているヘルパ関数です。

こちらではinfo()でエラーにならず、ログが出力されています。

@sumi21japan さんの環境情報と詳細なエラーメッセージを教えてください。

**Comment by sumi21japan** [comment]
ありがとうございます。

どうやらPHP7ServiceProviderの３０行目、$this->frameworkUncaughtExceptionHandler()でBadMethodCallExceptionになっていたようです。

何かインストールする時に忘れていることがあったのでしょうか。。
ご教示いただければ幸いです。

**Comment by sumi21japan** [comment]
お騒がせいたしました。
storageのパーミッションを変更したところ、動作しました。

**Comment by jumilla** [comment]
その箇所、PHP5で例外が発生した場合に呼ばれるコードですが、確かにエラーになりますね。

修正しました。
情報ありがとうございます！

**Comment by sumi21japan** [comment]
ありがとうございます！
